name: llm-cognition

channels: 
  - pytorch
  - conda-forge

dependencies: 
  - python=3.10
  - pip
  - matplotlib
  - pandas
  - jupyter
  - pytorch
  - cudatoolkit=11.7
  - pip: 
    #- torch 
    #- torchvision 
    #- torchaudio 
    - pytorch-pretrained-bert
    - pyllama 
    - transformers 
    - llama-cpp-python
